server:
  port: 8762
spring:
  application:
    name: consumer-server
  sleuth:
    enabled: false
    sampler:
      percentage: 1
  rabbitmq:
    host: 172.16.9.8
    port: 5672
    username: silverbox
    password: 123456
eureka:
  instance:
    lease-renewal-interval-in-seconds: 5      # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-expiration-duration-in-seconds: 10  # 发呆时间，即服务续约到期时间（缺省为90s）
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true
    ip-address: ${spring.cloud.client.ipAddress}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka